### ISSUE TITLE
Bug: Conditional rendering of field with promised validate throw error before submit

### ISSUE THREAD

**Issue by jean9696** [final-form/react-final-form#899] opened 2021-03-12 13:38 UTC
### Are you submitting a **bug report** or a **feature request**?

A bug report 

### What is the current behavior?

Since https://github.com/final-form/final-form/pull/369 we can't use `final-form` with conditional rendering coupled with validation function that returns a promise. 

The conditions are:
* initial render of the form without field `"buggyField"`
* other render with `"buggyField"`
* `"buggyField"` field with a validate function that returns a promise.

We get the following errors and we can't submit the form:

```
TypeError: Cannot set property 'validating' of undefined
```

``` 
TypeError: Cannot read property 'active' of undefined
```

it seems like `form.fields[name]` is deleted before function calls.

### Sandbox Link

[Sandbox](https://codesandbox.io/s/trusting-mendeleev-no919?file=/index.js)

### What's your environment?

```
    "final-form": "^4.20.2",
    "react-final-form": "^6.5.2",
```
### Other information

related to https://github.com/final-form/react-final-form/issues/894

**Comment by fzaninotto** [comment] 2021-03-18 07:49
I think https://github.com/final-form/final-form/pull/369 should be reverted is a fix for this bug doesn't come quickly. It's breaking many react-admin apps relying on react-final-form.

**Comment by gbakernet** [comment] 2021-03-25 00:49
I'm affected by this too actually. I think it's worth reverting
https://github.com/final-form/final-form/pull/409

**Comment by atomicacorn** [comment] 2021-04-30 09:27
Hi! Any update on this, or expectation on merging the PR? :)

**Closed** 2021-09-25 17:10 UTC

**Comment by erikras** [comment] 2021-09-29 10:37
Published fix in [`v4.20.3`](https://github.com/final-form/final-form/releases/tag/v4.20.3).

**Comment by av-k** [comment] 2022-03-03 04:57
Don't know how it happened, but at least since yesterday, this issue has been starting to reproduce again.
Can be reproduced using the same sandbox link (belove).

As you can see inside sandbox using **react-final-form** with the last verion **6.5.8** which is using the peer dependency **"final-form": "^4.20.4"**.

**Comment by av-k** [comment] 2022-03-10 11:31
@erikras any updates?
