### ISSUE TITLE
Reset multiple react final forms at one go

### ISSUE THREAD

**Issue by RAJdeep1990** [final-form/react-final-form#464] opened 2019-05-02 17:41 UTC
### Are you submitting a **bug report** or a **feature request**?

Seems like a bug, not entirely sure though if my approach is wrong.

### What is the current behavior?

I am using react-final-form and creating several forms in a loop (based on web API response data). I am using `form.reset` which works fine to reset each form separately. However, I have a "Reset All Forms" button which should reset all the forms which are there in the loop. 
In this scenario, `form.reset` is only resetting the last form in the loop and not the others.

Note: I am not using Redux. It is simple ReactJS and react-final-form.

Thank you for taking the time to go through my issue!

**Comment by RAJdeep1990** [comment] 2019-05-02 17:43
I am using react-final-form and creating several forms in a loop (based on web API response data). I am using form.reset which works fine to reset each form separately.

However, I have a "Reset All Forms" button which should reset all the forms which are there in the loop. In this scenario, form.reset is only resetting the last form in the loop and not the others.

Do you have any idea how to reset all the forms generated in a loop from an external button?

Note: I am not using Redux. It is simple ReactJS and react-final-form.

Thank you for taking the time to go through my issue!

**Comment by jweatherby** [comment] 2019-05-07 13:49
The approach I listed here, https://github.com/final-form/react-final-form/issues/419#issuecomment-488324864 could help. You have an external controller that manages a list of forms; when you need to reset them, just iterate over the forms. with `Object.values(this.forms).map(Form => Form.form.reset())`

**Comment by RAJdeep1990** [comment] 2019-05-07 19:02
Yes. Figured out on the day I posted it. Happy that is working!

**Comment by Andarist** [comment] 2019-05-18 08:55
If the issue is resolved, could you close it then? Thanks in advance!

**Closed** 2019-05-24 16:47 UTC
