### ISSUE TITLE
It does not fit into a large form

### ISSUE THREAD

**Issue by pierreneter** [final-form/react-final-form#228] opened 2018-04-19 07:17 UTC
### Are you submitting a **bug report** or a **feature request**?

**bug report** 

### What is the current behavior?

A form with > 50 fields.

### What is the expected behavior?

Smooth without lag

### What's your environment?

Node v8.10.0

```
{
  "final-form": "^4.5.2",
  "react-final-form": "^3.3.1"
}
```

**Comment by trisox** [comment] 2018-05-08 18:38
This Seems to be a problem with most forms have not found one that can handle over 80 fields Smoothly. Most of the time the problem is rerendering of the form when a onchange is fired so for every keystroke there is a rerender

**Comment by ernestopye** [comment] 2018-05-30 19:05
Have you looked at the subscription features? Make sure you're not subscribed to "values" otherwise every form element will re-render every single time any field changes. Shown here: [CodeSandbox](https://codesandbox.io/s/32r824vxy1) - Once you set this up, only the field you're modifying and any others that are specifically subscribed to changes to that field will.

**Comment by trisox** [comment] 2018-05-31 17:48
Yes this js the solution indeed using subscription

**Comment by erikras** [comment] 2018-05-31 18:13
Closing as answer has been provided. Thanks, guys.

**Closed by erikras** 2018-05-31 18:13 UTC
