### ISSUE TITLE
initialValues not populating

### ISSUE THREAD

**Issue by jasan-s** [final-form/react-final-form#275] opened 2018-06-08 21:46 UTC
### Are you submitting a **bug report** or a **feature request**?
Possible BUG

### What is the current behavior?
After Updating final-form(4.3.1 ==> 4.8.1 )& react-final-form(3.1.4 ==> 3.6.0)
The intialValues do not get populated.
### What is the expected behavior?
At first mount the intial values should be populated
### Sandbox Link

https://codesandbox.io/s/n993rvz3v4

### What's your environment?
"final-form": "^4.8.1"
"react-final-form": "^3.6.0"

### Other information

- From what i can see the issue first appeared at `react-final-form@3.5.2`  testing with  `react-final-form@3.5.1` it works as expected.

**Comment by erikras** [comment] 2018-06-08 21:50
I'm not sure I understand. Forgive me. Can you describe what should be happening in the sandbox and what is actually happening?

**Comment by jasan-s** [comment] 2018-06-08 22:15
@erikras  the initial values passed in are not being preloaded to the form fields. I just updated the sandbox `react-final-form` version to the latest 3.6.0.

**Comment by ashnur** [comment] 2018-06-12 15:01
@jasan-s I think it is working as intended. Your line `initialValues={this.state.data}` only runs once. You can verify this by doing a `console.log(this.state)` **inside** the render function that you are passing to Form (it shows the data set).

**Comment by erikras** [comment] 2018-06-12 15:59
After playing around with all the dependencies, I have determined that this is a bug with `react-dom@16.2.0`, which is fixed in `react-dom@16.3.0` and `react-dom@16.4.0`. Hard to tell [which fix it was](https://github.com/facebook/react/blob/master/CHANGELOG.md#react-dom-3), but...

**Closed by erikras** 2018-06-12 15:59 UTC
